import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-br from-[hsl(0,65%,40%)] to-[hsl(225,83%,40%)]">
        <h1 className="text-6xl font-extrabold text-stone-200">Tempest</h1>
      </main>
    </>
  );
};

export default Home;
